ARG BASE_IMAGE=messense/rust-musl-cross:armv7-musleabihf

FROM ${BASE_IMAGE} AS builder

WORKDIR /app

COPY rusttracks-web .
COPY rusttracks-contrib /rusttracks-contrib

RUN cargo build --release

FROM alpine:3.12

ENV RUST_BACKTRACE=full

WORKDIR /app
COPY --from=builder /app/target/armv7-unknown-linux-musleabihf/release/rusttracks-web ./
COPY --from=builder /app/static ./static

ENV ROCKET_ENV=prod
ENV ROCKET_ADDRESS=0.0.0.0
EXPOSE 8000

CMD ["./rusttracks-web"]